"""empty message

Revision ID: 0448fcec1f91
Revises: 4b5d66e7c9dd
Create Date: 2019-12-27 12:46:38.140704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0448fcec1f91'
down_revision = '4b5d66e7c9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=500), nullable=False),
    sa.Column('second_name', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('post', sa.Text(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('news_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_date'), 'orders', ['order_date'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('addition_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('comment_date', sa.Date(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('mark_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('date_archive', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'product_categories', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_categories', type_='unique')
    op.drop_table('order_product')
    op.drop_table('order_archive')
    op.drop_table('marks')
    op.drop_table('comments')
    op.drop_table('cart')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_order_date'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('news')
    op.drop_table('users')
    # ### end Alembic commands ###
