"""empty message

Revision ID: 1d0b9b3e3d75
Revises: 27db938fdc3f
Create Date: 2020-01-23 15:49:30.839148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d0b9b3e3d75'
down_revision = '27db938fdc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_archive', sa.Column('order_information', sa.JSON(), nullable=True))
    op.drop_constraint('order_archive_id_order_fkey', 'order_archive', type_='foreignkey')
    op.drop_constraint('order_archive_id_product_fkey', 'order_archive', type_='foreignkey')
    op.drop_column('order_archive', 'price')
    op.drop_column('order_archive', 'id_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_archive', sa.Column('id_product', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_archive', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_archive_id_product_fkey', 'order_archive', 'products', ['id_product'], ['id'])
    op.create_foreign_key('order_archive_id_order_fkey', 'order_archive', 'orders', ['id_order'], ['id'])
    op.drop_column('order_archive', 'order_information')
    # ### end Alembic commands ###
