"""empty message

Revision ID: 20f93a7bd324
Revises: e841042d0b57
Create Date: 2020-01-13 12:40:17.790528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f93a7bd324'
down_revision = 'e841042d0b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_role', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_role')
    # ### end Alembic commands ###
