"""add_ucid_to_Cart

Revision ID: 27db938fdc3f
Revises: 573814232571
Create Date: 2020-01-14 19:45:55.292291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27db938fdc3f'
down_revision = '573814232571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('ucid', sa.String(length=36), nullable=True))
    op.create_unique_constraint('unique_cart', 'cart', ['ucid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_cart', 'cart', type_='unique')
    op.drop_column('cart', 'ucid')
    # ### end Alembic commands ###
