"""empty message

Revision ID: 445363cf63e7
Revises: 1d0b9b3e3d75
Create Date: 2020-01-26 02:05:03.975831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445363cf63e7'
down_revision = '1d0b9b3e3d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=1000), nullable=False),
    sa.Column('e_mail', sa.String(length=1000), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('time_sent', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('comment_body', sa.Text(), nullable=False))
    op.drop_column('comments', 'body')
    op.add_column('order_archive', sa.Column('order_product', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_archive', 'order_product')
    op.add_column('comments', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'comment_body')
    op.drop_table('messages')
    # ### end Alembic commands ###
