"""empty message

Revision ID: 5b4369f48f5a
Revises: 82f2b445ff09
Create Date: 2020-01-09 13:09:57.287724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4369f48f5a'
down_revision = '82f2b445ff09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuidd', sa.String(length=36), nullable=True))
    op.drop_constraint('users_uuid_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['uuidd'])
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.VARCHAR(length=35), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_uuid_key', 'users', ['uuid'])
    op.drop_column('users', 'uuidd')
    # ### end Alembic commands ###
