"""empty message

Revision ID: 6affbb5babca
Revises: f3ba49aa93a8
Create Date: 2020-01-30 13:42:03.316341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6affbb5babca'
down_revision = 'f3ba49aa93a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_product_id_order_fkey', 'order_product', type_='foreignkey')
    op.create_foreign_key(None, 'order_product', 'orders', ['id_order'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.create_foreign_key('order_product_id_order_fkey', 'order_product', 'orders', ['id_order'], ['id'])
    # ### end Alembic commands ###
