"""add_ucid_to_Cart

Revision ID: 77185c3e5de9
Revises: f5dabcc9e35f
Create Date: 2020-01-13 20:59:38.549845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77185c3e5de9'
down_revision = 'f5dabcc9e35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('ucid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'cart', ['ucid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_column('cart', 'ucid')
    # ### end Alembic commands ###
