"""empty message

Revision ID: c20b634cdc1e
Revises: 0448fcec1f91
Create Date: 2019-12-27 14:37:17.554628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20b634cdc1e'
down_revision = '0448fcec1f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'thumbnail')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
