"""empty message

Revision ID: e841042d0b57
Revises: 5b4369f48f5a
Create Date: 2020-01-09 13:12:25.025018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e841042d0b57'
down_revision = '5b4369f48f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.drop_constraint('users_uuidd_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['uuid'])
    op.drop_column('users', 'uuidd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uuidd', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_uuidd_key', 'users', ['uuidd'])
    op.drop_column('users', 'uuid')
    # ### end Alembic commands ###
