"""empty message

Revision ID: ff25e4d94a40
Revises: 5cb44efe9a11
Create Date: 2020-01-08 15:25:00.482843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff25e4d94a40'
down_revision = '5cb44efe9a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###

